### ISSUE TITLE
Questions about session_data generation

### ISSUE THREAD

**Issue by YukioZzz** [gisbi-kim/lt-mapper#1]
Hi, I found that the `SC-PGO` saver in `FAST-LIO-SLAM` will not save `singlesession_posegraph.g2o` and `SCDs` which are required by lt-mapper. 

So actually, we can only use `SC-LIO-SLAM` saver to generate session data right?

**Comment by gisbi-kim** [comment]
sc-a-loam (https://github.com/gisbi-kim/SC-A-LOAM ) currently suppports meta-data saver (see https://github.com/gisbi-kim/SC-A-LOAM/blob/321cb4b07b7815c114237ce5d87014d2e46b972c/src/laserPosegraphOptimization.cpp#L132) 

the file laserPosegraphOptimization.cpp in sc-a-loam does not yet be physically copied (or syncronized) within the fast-lio-slam repo, but I think you can easily copy and paste the file to the directory here https://github.com/gisbi-kim/FAST_LIO_SLAM/tree/main/SC-PGO/src
