### ISSUE TITLE
Great job, and is the code about LT-removert and LT-map modules  release?

### ISSUE THREAD

**Issue by chengwei0427** [gisbi-kim/lt-mapper#2]

**Comment by gisbi-kim** [comment]
hi, @chengwei0427, sorry for the late update, I've been busy having job interviews. 
I'll upload the research-level code (I mean, it might be dirty) by this week. 
, with a simple how-to-use-introduction video on youtube. 

ps. I have a plan to refactor the codes after the manuscript review is released on Jan.

**Comment by chengwei0427** [comment]
Glad to hear that you have a plan to refactor the codes.
I'll check and update.

**Comment by littleporkbelly** [comment]
Thanks for sharing the great content and hope your job searching went well! I'm wondering if there is any updates on the release schedule?

**Comment by wienans** [comment]
Hi thanks for the release would also be interested to the additional modules, even if the code is a bit dirty :D

**Comment by gisbi-kim** [comment]
Dear all guys,
sorry for the late, the initial code is uploaded, and the tutorial video will be followed. Thanks!
