### ISSUE TITLE
will the LT-removert and LT-map modules released?

### ISSUE THREAD

**Issue by TurtleZhong** [gisbi-kim/lt-mapper#4]
Hi, I have read your paper and I thinks this is really great job and I wanna try it, So will the LT-removert and LT-map modules released?

**Comment by lincob** [comment]
From README, hence the name :
LT-removert and LT-map modules will be released. -> It is taking a little more time. I could say that the complete codes will be shared before the conference (May, 2022).

Conference is on the last week of may.

**Comment by gisbi-kim** [comment]
Dear guys, @TurtleZhong and @lincob 
sorry for the late, 
the initial code is uploaded, and the tutorial video will be followed. Thanks!
